FashionAdTitle: FashionAd
CoordinationList: Coordination List
NoCoordinationList: There is no coordination list.
ItemList: Item List
AddItem: Add Item
BaseInfo: Base Info
AddCoordination: Add New Coordination
ModifyBaseInfo: Modify Base Info
YourRating: Your Rating
CoordinationTitle: Title
MyPage name@Text: #{name}'s MyPage
UserList: User List
ItemName: Name
ItemKind: Kind
ItemLink: Link
ItemPrice: Price
CoordinationDesc: Description
TooSmallPrice: Price is too small.
RateComment: Comment
UserCoordinations: Coordinations
UserFollowing: Following
UserFollowers: Followers
UserInfo: User Info
YourProfile: Your Profile
UserProfile name@Text: #{name}'s Profile
Login: Login
Logout: Logout
Welcome: Welcome
ItIsYourself: It is yourself.
