Default: &defaults
  host: "ec2-175-41-201-181.ap-northeast-1.compute.amazonaws.com"
  port: 3000
  copyright: Insert copyright statement here

Development:
  <<: *defaults

Test:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  approot: "http://www.example.com"
  <<: *defaults