Default: &defaults
  host: "localhost"
  port: 3000
  copyright: Insert copyright statement here

Development:
  approot: ""
  <<: *defaults

Test:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  approot: "http://www.example.com"
  <<: *defaults