Default: &defaults
  database: fashionad.sqlite3

Development:
  <<: *defaults

Test:
  database: fashionad_test.sqlite3
  <<: *defaults

Staging:
  database: fashionad_staging.sqlite3
  <<: *defaults

Production:
  database: fashionad_production.sqlite3
  <<: *defaults